"""Domain package defining core soil science entities and validation rules."""

from backend.domain.exceptions import (
    InvalidClassificationError,
    InvalidCoordinateError,
    InvalidDatasetMetadataError,
    InvalidEnvironmentalContextError,
    InvalidHydrologicContextError,
    InvalidLandLimitationsError,
    InvalidLayerError,
    InvalidLayerMeasurementsError,
    InvalidObservationError,
    InvalidProfileError,
    InvalidPropertyError,
    InvalidSoilTextureError,
)
from backend.domain.value_objects import (
    ChemicalProperties,
    Coordinate,
    DatasetMetadata,
    EnvironmentalContext,
    HydraulicProperties,
    HydrologicContext,
    LandLimitations,
    LayerMeasurements,
    PhysicalProperties,
    PropertyType,
    SoilClassification,
    SoilLayer,
    SoilObservation,
    SoilProfile,
    SoilProperty,
    SoilTexture,
    Unit,
)

__all__ = [
    "Coordinate",
    "SoilProperty",
    "PropertyType",
    "Unit",
    "SoilClassification",
    "SoilLayer",
    "SoilProfile",
    "SoilObservation",
    "EnvironmentalContext",
    "HydrologicContext",
    "LandLimitations",
    "SoilTexture",
    "PhysicalProperties",
    "ChemicalProperties",
    "HydraulicProperties",
    "LayerMeasurements",
    "DatasetMetadata",
    "InvalidCoordinateError",
    "InvalidPropertyError",
    "InvalidClassificationError",
    "InvalidLayerError",
    "InvalidProfileError",
    "InvalidObservationError",
    "InvalidEnvironmentalContextError",
    "InvalidHydrologicContextError",
    "InvalidLandLimitationsError",
    "InvalidSoilTextureError",
    "InvalidLayerMeasurementsError",
    "InvalidDatasetMetadataError",
]
